name: Go

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      - name: Build
        run: |
          mkdir release/
          GOOS=linux GOARCH=amd64 go build -v -o release/git-new-linux-amd64

      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: git-new-linux
          path: release/

      - name: Create Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create \
            --verify-tag \
            --title "Release ${{ github.ref_name }}" \
            "${{ github.ref_name }}" \
            release/git-new-linux-amd64
